apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
resources:
- ../../base
labels:
- includeSelectors: true
  pairs:
    env: production
patches:
- path: deployment-patch.yaml